#' @param dtoken The Dropbox token generated by \code{\link{dropbox_auth}}.
#'   rDrop2 will try to automatically locate your local credential cache and use
#'   them. However, if the credentials are not found, the function will initiate
#'   a new authentication request. You can override this by pointing to a
#'   different location where your credentials are stored.

